export const SETTINGS_QUERY_KEY = 'GLOBAL_SETTINGS';
export const FAQS_QUERY_KEY = 'FAQS';
export const BRANCHES_QUERY_KEY = 'BRANCHES';
export const BLOG_QUERY_KEY = 'BLOG';
export const GALLERY_QUERY_KEY = 'GALLERY';
export const FEATURED_GALLARY_QUERY_KEY = 'FEATURED_GALLARY';
export const CLIENTS_QUERY_KEY = 'CLIENTS';
export const INACTION_QUERY_KEY = 'INACTION';
